sudo: false

language: node_js

node_js:
  - "8"
  - "9"
  - "10"

notifications:
  disabled: true

before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

install:
  - npm install -g codecov
  - npm install

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm test
  - codecov
